### ISSUE TITLE
2016 Space Narratives

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/2016.Mozillafestival.org#23]
Here is the full list of Space and experience narratives for MozFest 2016 -
Each space has its own issue with the narrative for @KevZawacki to triage for a one voice perspective. Where applicable I added the Space Wranglers to the issue too. Once all narratives have been uploaded and received some Kevin love they are ready for @mmmavis @edrushka magic 
- [ ]  Moz Ex  (Art Exhibit) - #24 
- [ ]  A tale of two cities - the dilemmas of shared connected spaces #46  
- [ ]  Digital Arts and Culture - #25
- [ ] Open Science #41
- [ ] Journalism #39
- [ ] Fuel the Movement #40
- [ ] Youth Zone #36
- [ ] Demystify the Web  #42
- [ ] Badges #37
- [ ]  Localisation
- [x] All narratives have been uploaded
- [ ] All narratives are ready for Ricardo
- [ ] All names have been confirmed with the SW

**Comment by Saallen** [comment]
@KevZawacki a common thread is that ppl are destinctively calling for sessions or types of sessions. if we could leave this sentence to the end of each narrative so that in August we can just simply remove the line without distrupting the text that would be great.

**Comment by KevZawacki** [comment]
@Saallen A heads up on process: I'm revising these as they come in -- but will hold off on sharing until they've all come in and been edited. (So I can take a look at them as a whole and ensure they fit together.)

Re: your above comment -- so, we should end each Space description with a sentence like, "If you have an idea for a session that fits within the xx Space, visit our Call for Proposals page"?

**Comment by Saallen** [comment]
@KevZawacki I think we should add that line in at the top of the page when describing what is taking place on the page. what do you think @edrushka

**Comment by edrushka** [comment]
Sure! 

So to summarize:
- all space descriptions will go on what we currently call the sessions page:  https://2015.mozillafestival.org/sessions
- we'll rename this page 'spaces and sessions'
- we'll edit the para at the top of the page to explain what's happening
- we'll link to this page directly from the Call for Proposals form, where we ask people to pick what space they are submitting to
