### ISSUE TITLE
Review new design elements for use on site

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/2016.Mozillafestival.org#82]
When the 2016 Style Guide is complete, see if there are any elements (e.g. textures, backgrounds, colours) we could add to the landing page in mid-September.

**Comment by edrushka** [comment]
@sabrina do you have any recommendations here?

**Comment by edrushka** [comment]
@sabrinang do you have any recommendations here?

**Comment by edrushka** [comment]
@sabrinang do you have any recommendations here?

**Comment by edrushka** [comment]
@sabrinang do you have any recommendations here?

**Comment by alanmoo** [comment]
_takes away @edrushka's coffee_

**Comment by edrushka** [comment]
Sorry - GH wasn't responding so I just kept pressing 'comment' 😆

**Comment by kristinashu** [comment]
We should update:
- top left logo color
- fav icon color
- footer background gradients to solid color
- title color
- link and button color
- icons (update style and color) 
- photo banner treatment 
- table color
- About background gradient

@sabrinang let me know if you think of anything else.

Examples:
<img width="221" alt="screen shot 2016-09-08 at 9 28 37 am" src="https://cloud.githubusercontent.com/assets/1068783/18357786/1b05440a-75a7-11e6-9a44-2c4d884e9238.png">
<img width="1079" alt="screen shot 2016-09-08 at 9 28 42 am" src="https://cloud.githubusercontent.com/assets/1068783/18357790/1fac3072-75a7-11e6-91a0-56dd11289e6d.png">
<img width="362" alt="screen shot 2016-09-08 at 9 28 03 am" src="https://cloud.githubusercontent.com/assets/1068783/18357743/f1c16420-75a6-11e6-86e1-0b163dbc6c9e.png">
<img width="1416" alt="screen shot 2016-09-08 at 9 28 27 am" src="https://cloud.githubusercontent.com/assets/1068783/18357784/164c809a-75a7-11e6-8f6b-22ac3e6aa0f1.png">
<img width="977" alt="screen shot 2016-09-08 at 9 28 16 am" src="https://cloud.githubusercontent.com/assets/1068783/18357765/05b57264-75a7-11e6-82f3-2fbd219e7c77.png">
<img width="293" alt="screen shot 2016-09-14 at 9 44 24 am" src="https://cloud.githubusercontent.com/assets/1068783/18521253/3b147730-7a60-11e6-845a-558a3202d46c.png">

**Comment by kristinashu** [comment]
Comps are here: https://redpen.io/p/nfb876a7968c868f1b
- [x] top left logo color - Blue #362FC1 and Pink #FA1BAB
- [x] fav icons - https://drive.google.com/open?id=0B2irLVDJivhLajZDNFE5UTF3T0U
- [x] footer background gradients to solid color - Blue #362FC1
- [x] title text color - Blue #362FC1
- [x] link text and button color - Pink #FA1BAB
- [x] icons (update style and color) - [Location Page](https://redpen.io/rzb54ae3c93171113f)
- [x] photo banner treatment (https://redpen.io/nw70a0d8f24c9bc983) - Keeping gradient but updated to 2016 colors and added diagonal lines (because we don't have the original photoshop file with all the banner images, redoing these without a gradient will be time consuming). @sabrinang @xmatthewx let me know if that works for you?
- [x] table color on [What to Expect page](https://mozillafestival.org/expect) - The 3 colors can just be Blue #362FC1
- [x] [About](https://mozillafestival.org/about) background gradient to Purple #6D22AF

**Comment by kristinashu** [comment]
These are all done ^

@xmatthewx or @sabrinang can you please review?

Opened https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/93 for banner image production.

**Comment by xmatthewx** [comment]
Am I just reviewing the redpen? Overall looks good to me. I'll let @sabrinang weigh in on the details.

**Comment by kristinashu** [comment]
Cool, closing this ticket but @sabrinang please feel free to add comments in redpen.
