### ISSUE TITLE
Implement new design elements for use on site

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/2016.Mozillafestival.org#94]
Based on design work done in #82

Comps are here: https://redpen.io/p/nfb876a7968c868f1b

Updates:
- [x] top left logo (Pink and White) - https://drive.google.com/open?id=0B2irLVDJivhLOUhvRm1aRF9tZnM
- [x] fav icons (there are a bunch of sizes there, only use what you need) - https://drive.google.com/drive/folders/0B2irLVDJivhLSjhkdjUwbGZMc00?usp=sharing
- [x] footer background gradients to solid color - Blue #362FC1
- [x] title text color - Blue #362FC1
- [x] link text and button color - Pink #FA1BAB
- [x] icons on [Location Page](https://mozillafestival.org/location) - https://drive.google.com/open?id=0B2irLVDJivhLd21wWmVyTlNTbnM
- [x] table color on [What to Expect page](https://mozillafestival.org/expect) - The 3 colors can just be Blue #362FC1
- [x] [About](https://mozillafestival.org/about) background gradient to Purple #6D22AF

**Comment by kristinashu** [comment]
@alanmoo I'm still gathering assets but here's a summary of the general design changes (excludes Home page https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/81 and Wrangler page https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/86 which I will open separate tickets for once the design is approved).

**Comment by mmmavis** [comment]
note for myself: this is ready for implementation

**Comment by kristinashu** [comment]
Update the fav icon link https://drive.google.com/drive/folders/0B2irLVDJivhLSjhkdjUwbGZMc00?usp=sharing

**Comment by mmmavis** [comment]
I believe this has been taken care of. @kristinashu can you help verify and close this ticket if things look good?

**Comment by kristinashu** [comment]
Everything I mentioned above ^ looks great!

Couple additional instances of the old colors tho. Are you able to search for that old red and replace with our new blue?
<img width="855" alt="screen shot 2016-09-22 at 4 59 07 pm" src="https://cloud.githubusercontent.com/assets/1068783/18769973/77643a2c-80e6-11e6-8d76-f4c2833e919a.png">
<img width="910" alt="screen shot 2016-09-22 at 5 02 46 pm" src="https://cloud.githubusercontent.com/assets/1068783/18769974/7769a0d4-80e6-11e6-8e53-d86ee15ace53.png">

**Comment by mmmavis** [comment]
DONE!
